config/routes.rb
Rails.application.routes.draw do
  resources :ref_type_fields
  resources :ref_meta
  resources :ref_attributes
  resources :refs, :only => [:index,:show,:edit,:update,:destroy]
  resources :reftypes

  root 'refs#index'

  get 'bibtexify/' => 'bibtexifies#download'
  get  'ref_meta/:reftype_name/:slug/new' => 'ref_meta#new'
  get 'reftypes/:reftype_id/new_field' => 'ref_type_fields#type_new'
  get 'uusi/:type' => 'uusi#new'
  post 'uusi' => 'uusi#create'

end

app/controllers/reftypes_controller.rb
class ReftypesController < ApplicationController
  before_action :set_reftype, only: [:show, :edit, :update, :destroy]

  # GET /reftypes
  # GET /reftypes.json
  def index
    @reftypes = Reftype.all
  end

  # GET /reftypes/1
  # GET /reftypes/1.json
  def show
    @required = @reftype.requiredFields
    @optional = @reftype.optionalFields
    @cat2 = @reftype.required2Fields
    @cat3 = @reftype.required3Fields
  end

  # GET /reftypes/new
  def new
    @reftype = Reftype.new
  end

  # GET /reftypes/1/edit
  def edit
  end

  # POST /reftypes
  # POST /reftypes.json
  def create
    @reftype = Reftype.new(reftype_params)

    respond_to do |format|
      if @reftype.save
        format.html { redirect_to @reftype, notice: 'Uusi viitetyyppi luotu onnistuneesti.' }
        format.json { render :show, status: :created, location: @reftype }
      else
        format.html { render :new }
        format.json { render json: @reftype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reftypes/1
  # PATCH/PUT /reftypes/1.json
  def update
    respond_to do |format|
      if @reftype.update(reftype_params)
        format.html { redirect_to @reftype, notice: 'Reftype was successfully updated.' }
        format.json { render :show, status: :ok, location: @reftype }
      else
        format.html { render :edit }
        format.json { render json: @reftype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reftypes/1
  # DELETE /reftypes/1.json
  def destroy
    @reftype.destroy
    respond_to do |format|
      format.html { redirect_to reftypes_url, notice: 'Reftype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reftype
      @reftype = Reftype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reftype_params
      params.require(:reftype).permit(:name)
    end
end

app/helpers/reftypes_helper.rb
module ReftypesHelper
end

app/views/reftypes/_form.html.erb
<%= form_for(@reftype) do |f| %>
  <% if @reftype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reftype.errors.count, "error") %> prohibited this reftype from being saved:</h2>

      <ul>
      <% @reftype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Nimi' %><br>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Tallenna',class:'btn btn-default btn-lg' %>
  </div>
<% end %>

app/views/reftypes/edit.html.erb
<h1>Muokkaa viitetyyppiä</h1>

<%= render 'form' %>

<%= link_to 'Takaisin', @reftype %> |

app/views/reftypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Viitteiden tyypit</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nimi</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @reftypes.each do |reftype| %>
      <tr>
        <td><%= link_to  reftype.name ,reftype%></td>
        <td><%= link_to 'Muokkaa', edit_reftype_path(reftype) %></td>
        <td><%= link_to 'Poista', reftype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Luo uusi tyyppi', new_reftype_path %>

app/views/reftypes/new.html.erb
<h1>Luo uusi viitetyyppi</h1>

<%= render 'form' %>

<%= link_to 'Takaisin', reftypes_path %>

app/views/reftypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1>  <%= @reftype.name %></h1>
<%= link_to 'Muokkaa nimeä', edit_reftype_path(@reftype) %> |
  <%= link_to 'Lisää kenttä', '/reftypes/'+@reftype.id.to_s+'/new_field'%>
  <h2>Pakolliset kentät</h2>
  <table class="table table-striped">
    <tr>
      <th>Kenttä</th>
      <th></th>
    </tr>
    <% @required.each do |a| %>
    <tr>
      <td><%= link_to a.name, edit_ref_type_field_path(a.ref_type_fields[0]) %></td>
      <td><%= link_to 'Muokkaa', edit_ref_attribute_path(a) %> </td>
      <td><%= link_to 'Poista', a, method: :delete, data: { confirm: 'Oletko varma?' } %></td>
    </tr>

    <% end %>
  </table class="table table-striped">
  <h2>Pakolliset kentätä (ja/tai)</h2>
<table>
<% @cat2.each do |a| %>
    <tr>
      <td><%= a.name %></td>
      <td><%= link_to 'Muokkaa', edit_ref_attribute_path(a) %> </td>
      <td><%= link_to 'Poista', a, method: :delete, data: { confirm: 'Oletko varma?' } %></td>
    </tr>
<% end %>
</table>
<h2>Pakolliset kentätä (ja/tai)</h2>
<table class="table table-striped">
  <% @cat3.each do |a| %>
      <tr>
        <td><%= a.name %></td>
        <td><%= link_to 'Muokkaa', edit_ref_attribute_path(a) %> </td>
        <td><%= link_to 'Poista', a, method: :delete, data: { confirm: 'Oletko varma?' } %></td>
      </tr>
  <% end %>
</table>
  <h2>Vapaavalintaiset kentät</h2>
<table class="table table-striped">
<% @optional.each do |a| %>
    <tr>
      <td><%= a.name %></td>
      <td><%= link_to 'Muokkaa', edit_ref_attribute_path(a) %> </td>
      <td><%= link_to 'Poista', a, method: :delete, data: { confirm: 'Oletko varma?' } %></td>
    </tr>

<% end %>
</table>
</p>


<%= link_to 'Takaisin', reftypes_path %>