config/routes.rb
Rails.application.routes.draw do
  resources :ref_type_fields
  resources :ref_meta
  resources :ref_attributes
  resources :refs, :only => [:index,:show,:edit,:update,:destroy]
  resources :reftypes

  root 'refs#index'

  get 'bibtexify/' => 'bibtexifies#download'
  get  'ref_meta/:reftype_name/:slug/new' => 'ref_meta#new'
  get 'reftypes/:reftype_id/new_field' => 'ref_type_fields#type_new'
  get 'uusi/:type' => 'uusi#new'
  post 'uusi' => 'uusi#create'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.erb
<%= link_to 'Referenssit', refs_path %> | <%= link_to 'Referenssi tyypit', reftypes_path %> |<%= link_to 'Attribuutit', ref_attributes_path %> |  <%= link_to 'Meta', ref_meta_path %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Viitteet', root_path, class: 'navbar-brand' %>
      <%= link_to 'Referenssi tyypit', reftypes_path, class: 'navbar-brand'  %>
      <%= link_to 'Attribuutit', ref_attributes_path, class: 'navbar-brand'  %>
      <%= link_to 'Meta', ref_meta_path, class: 'navbar-brand'  %>
      <%= link_to 'Lataa BibTeX-tiedosto', '/bibtexify', class: 'navbar-brand'  %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Minip" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Minip" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>